-- ============================================================================
-- Sort It Out — factory card dictionary seed (generated file, do not edit by hand)
--
-- Source:    supabase/seed/factory_cards.json
-- Regenerate: pnpm seed:factory
-- Cards:     283
--
-- Every factory card is original to this project and carries both an English and a
-- Spanish rendering of the same canonical concept.
-- ============================================================================

insert into public.factory_cards (id, text_en, text_es) values
  ('f-cold-pizza-for-breakfast', 'Cold pizza for breakfast', 'Pizza fría en el desayuno'),
  ('f-fresh-bread-from-the-oven', 'Fresh bread from the oven', 'Pan recién salido del horno'),
  ('f-melted-cheese', 'Melted cheese', 'Queso fundido'),
  ('f-very-spicy-salsa', 'Very spicy salsa', 'Salsa muy picante'),
  ('f-chocolate-with-sea-salt', 'Chocolate with sea salt', 'Chocolate con sal marina'),
  ('f-watermelon-on-a-hot-day', 'Watermelon on a hot day', 'Sandía en un día de calor'),
  ('f-black-coffee-with-no-sugar', 'Black coffee with no sugar', 'Café solo sin azúcar'),
  ('f-ice-cream-that-tastes-like-bubble-gum', 'Ice cream that tastes like bubble gum', 'Helado con sabor a chicle'),
  ('f-cold-soup', 'Cold soup', 'Sopa fría'),
  ('f-burnt-toast', 'Burnt toast', 'Tostada quemada'),
  ('f-homemade-lemonade', 'Homemade lemonade', 'Limonada casera'),
  ('f-an-overripe-banana', 'An overripe banana', 'Un plátano demasiado maduro'),
  ('f-crunchy-pickles', 'Crunchy pickles', 'Pepinillos crujientes'),
  ('f-breakfast-served-for-dinner', 'Breakfast served for dinner', 'Desayuno servido para cenar'),
  ('f-leftovers-on-the-third-day', 'Leftovers on the third day', 'Sobras al tercer día'),
  ('f-popcorn-at-the-cinema', 'Popcorn at the cinema', 'Palomitas en el cine'),
  ('f-boiled-vegetables-with-no-salt', 'Boiled vegetables with no salt', 'Verduras hervidas sin sal'),
  ('f-a-stew-cooked-by-a-grandparent', 'A stew cooked by a grandparent', 'Un guiso cocinado por un abuelo'),
  ('f-sparkling-water', 'Sparkling water', 'Agua con gas'),
  ('f-pineapple-on-pizza', 'Pineapple on pizza', 'Piña en la pizza'),
  ('f-warm-milk-before-bed', 'Warm milk before bed', 'Leche caliente antes de dormir'),
  ('f-an-avocado-that-is-still-a-bit-green', 'An avocado that is still a bit green', 'Un aguacate todavía un poco verde'),
  ('f-food-from-a-street-cart', 'Food from a street cart', 'Comida de un puesto callejero'),
  ('f-blowing-out-birthday-candles', 'Blowing out birthday candles', 'Soplar las velas de cumpleaños'),
  ('f-salad-with-no-dressing', 'Salad with no dressing', 'Ensalada sin aliño'),
  ('f-free-samples-at-the-market', 'Free samples at the market', 'Muestras gratis en el mercado'),
  ('f-peanut-butter-straight-from-the-spoon', 'Peanut butter straight from the spoon', 'Crema de cacahuete directa de la cuchara'),
  ('f-soup-that-is-far-too-hot', 'Soup that is far too hot', 'Sopa demasiado caliente'),
  ('f-sharing-one-dessert-between-two', 'Sharing one dessert between two', 'Compartir un postre entre dos'),
  ('f-cooking-with-every-pot-in-the-kitchen', 'Cooking with every pot in the kitchen', 'Cocinar usando todas las ollas de la cocina'),
  ('f-instant-noodles-at-midnight', 'Instant noodles at midnight', 'Fideos instantáneos a medianoche'),
  ('f-a-perfectly-ripe-peach', 'A perfectly ripe peach', 'Un melocotón en su punto'),
  ('f-olives', 'Olives', 'Aceitunas'),
  ('f-toast-with-butter-and-jam', 'Toast with butter and jam', 'Tostada con mantequilla y mermelada'),
  ('f-cold-chips-at-the-bottom-of-the-bag', 'Cold chips at the bottom of the bag', 'Patatas fritas frías al fondo de la bolsa'),
  ('f-eating-a-meal-with-your-hands', 'Eating a meal with your hands', 'Comer una comida con las manos'),
  ('f-a-restaurant-menu-with-too-many-pages', 'A restaurant menu with too many pages', 'Una carta de restaurante con demasiadas páginas'),
  ('f-tasting-a-food-you-cannot-name', 'Tasting a food you cannot name', 'Probar una comida cuyo nombre no conoces'),
  ('f-the-last-slice-of-cake', 'The last slice of cake', 'El último trozo de tarta'),
  ('f-herbal-tea-after-a-long-day', 'Herbal tea after a long day', 'Infusión de hierbas después de un día largo'),
  ('f-going-camping', 'Going camping', 'Ir de camping'),
  ('f-board-games-with-friends', 'Board games with friends', 'Juegos de mesa con amigos'),
  ('f-singing-in-the-shower', 'Singing in the shower', 'Cantar en la ducha'),
  ('f-a-long-bike-ride', 'A long bike ride', 'Un paseo largo en bicicleta'),
  ('f-doing-a-jigsaw-puzzle', 'Doing a jigsaw puzzle', 'Armar un rompecabezas'),
  ('f-dancing-badly-on-purpose', 'Dancing badly on purpose', 'Bailar mal a propósito'),
  ('f-reading-in-bed', 'Reading in bed', 'Leer en la cama'),
  ('f-learning-a-new-language', 'Learning a new language', 'Aprender un idioma nuevo'),
  ('f-swimming-in-the-sea', 'Swimming in the sea', 'Nadar en el mar'),
  ('f-karaoke-in-front-of-strangers', 'Karaoke in front of strangers', 'Karaoke delante de desconocidos'),
  ('f-gardening-on-a-saturday-morning', 'Gardening on a Saturday morning', 'Jardinería un sábado por la mañana'),
  ('f-watching-the-sun-go-down', 'Watching the sun go down', 'Ver caer el sol'),
  ('f-building-furniture-from-instructions', 'Building furniture from instructions', 'Montar muebles siguiendo instrucciones'),
  ('f-taking-photographs-of-your-food', 'Taking photographs of your food', 'Fotografiar tu comida'),
  ('f-going-to-the-gym-very-early', 'Going to the gym very early', 'Ir al gimnasio muy temprano'),
  ('f-walking-with-no-destination', 'Walking with no destination', 'Caminar sin rumbo'),
  ('f-playing-cards-with-grandparents', 'Playing cards with grandparents', 'Jugar a las cartas con los abuelos'),
  ('f-colouring-in-a-drawing', 'Colouring in a drawing', 'Colorear un dibujo'),
  ('f-learning-to-juggle', 'Learning to juggle', 'Aprender a hacer malabares'),
  ('f-walking-uphill-for-an-hour', 'Walking uphill for an hour', 'Caminar cuesta arriba durante una hora'),
  ('f-a-nap-on-sunday-afternoon', 'A nap on Sunday afternoon', 'Una siesta el domingo por la tarde'),
  ('f-cleaning-the-whole-house-in-one-day', 'Cleaning the whole house in one day', 'Limpiar toda la casa en un día'),
  ('f-trying-a-completely-new-haircut', 'Trying a completely new haircut', 'Probar un corte de pelo totalmente nuevo'),
  ('f-cooking-for-a-lot-of-people', 'Cooking for a lot of people', 'Cocinar para mucha gente'),
  ('f-fishing-in-complete-silence', 'Fishing in complete silence', 'Pescar en completo silencio'),
  ('f-watching-birds-from-a-window', 'Watching birds from a window', 'Observar pájaros desde una ventana'),
  ('f-video-calls-with-the-whole-family', 'Video calls with the whole family', 'Videollamadas con toda la familia'),
  ('f-ice-skating-for-the-first-time', 'Ice skating for the first time', 'Patinar sobre hielo por primera vez'),
  ('f-running-in-the-rain', 'Running in the rain', 'Correr bajo la lluvia'),
  ('f-writing-by-hand-in-a-notebook', 'Writing by hand in a notebook', 'Escribir a mano en un cuaderno'),
  ('f-finishing-a-crossword', 'Finishing a crossword', 'Terminar un crucigrama'),
  ('f-playing-hide-and-seek', 'Playing hide and seek', 'Jugar al escondite'),
  ('f-learning-a-card-trick', 'Learning a card trick', 'Aprender un truco de cartas'),
  ('f-repairing-something-yourself', 'Repairing something yourself', 'Arreglar algo tú mismo'),
  ('f-spending-an-afternoon-in-a-museum', 'Spending an afternoon in a museum', 'Pasar una tarde en un museo'),
  ('f-sleeping-outdoors-with-no-tent', 'Sleeping outdoors with no tent', 'Dormir al aire libre sin tienda'),
  ('f-trying-pottery-for-the-first-time', 'Trying pottery for the first time', 'Probar la cerámica por primera vez'),
  ('f-singing-happy-birthday-out-loud', 'Singing happy birthday out loud', 'Cantar el cumpleaños feliz en voz alta'),
  ('f-watching-the-same-film-again', 'Watching the same film again', 'Volver a ver la misma película'),
  ('f-feeding-ducks-at-a-pond', 'Feeding ducks at a pond', 'Dar de comer a los patos en un estanque'),
  ('f-riding-a-rollercoaster', 'Riding a rollercoaster', 'Subir a una montaña rusa'),
  ('f-playing-football-in-the-street', 'Playing football in the street', 'Jugar al fútbol en la calle'),
  ('f-sitting-beside-a-campfire', 'Sitting beside a campfire', 'Sentarse junto a una fogata'),
  ('f-sleeping-in-a-hammock', 'Sleeping in a hammock', 'Dormir en una hamaca'),
  ('f-building-a-sandcastle', 'Building a sandcastle', 'Construir un castillo de arena'),
  ('f-flying-a-kite-on-a-windy-day', 'Flying a kite on a windy day', 'Volar una cometa en un día de viento'),
  ('f-teaching-someone-to-swim', 'Teaching someone to swim', 'Enseñar a alguien a nadar'),
  ('f-painting-a-room-a-new-colour', 'Painting a room a new colour', 'Pintar una habitación de un color nuevo'),
  ('f-playing-an-instrument-badly', 'Playing an instrument badly', 'Tocar un instrumento mal'),
  ('f-sheets-that-were-washed-today', 'Sheets that were washed today', 'Sábanas lavadas hoy'),
  ('f-a-very-heavy-blanket', 'A very heavy blanket', 'Una manta muy pesada'),
  ('f-old-family-photographs', 'Old family photographs', 'Fotografías familiares antiguas'),
  ('f-shoes-that-squeak-when-you-walk', 'Shoes that squeak when you walk', 'Zapatos que chirrían al caminar'),
  ('f-a-phone-with-two-per-cent-battery', 'A phone with two per cent battery', 'Un teléfono con dos por ciento de batería'),
  ('f-a-pen-that-will-not-write', 'A pen that will not write', 'Un bolígrafo que no escribe'),
  ('f-popping-bubble-wrap', 'Popping bubble wrap', 'Explotar plástico de burbujas'),
  ('f-a-hammock-in-the-garden', 'A hammock in the garden', 'Una hamaca en el jardín'),
  ('f-thick-woollen-socks', 'Thick woollen socks', 'Calcetines gruesos de lana'),
  ('f-an-old-chair-that-is-very-comfortable', 'An old chair that is very comfortable', 'Una silla vieja muy cómoda'),
  ('f-sunglasses-that-fit-perfectly', 'Sunglasses that fit perfectly', 'Gafas de sol que quedan perfectas'),
  ('f-an-umbrella-in-strong-wind', 'An umbrella in strong wind', 'Un paraguas con viento fuerte'),
  ('f-a-table-that-wobbles', 'A table that wobbles', 'Una mesa que se tambalea'),
  ('f-a-brand-new-empty-notebook', 'A brand new empty notebook', 'Un cuaderno nuevo y vacío'),
  ('f-small-lights-strung-across-a-room', 'Small lights strung across a room', 'Lucecitas colgadas por la habitación'),
  ('f-an-alarm-clock-that-is-too-loud', 'An alarm clock that is too loud', 'Un despertador demasiado ruidoso'),
  ('f-a-shopping-trolley-with-one-bad-wheel', 'A shopping trolley with one bad wheel', 'Un carrito de la compra con una rueda mala'),
  ('f-a-very-sharp-kitchen-knife', 'A very sharp kitchen knife', 'Un cuchillo de cocina muy afilado'),
  ('f-clothes-handed-down-from-a-relative', 'Clothes handed down from a relative', 'Ropa heredada de un familiar'),
  ('f-a-jar-that-will-not-open', 'A jar that will not open', 'Un frasco que no se abre'),
  ('f-slippers-waiting-by-the-door', 'Slippers waiting by the door', 'Pantuflas esperando junto a la puerta'),
  ('f-a-paper-map', 'A paper map', 'Un mapa de papel'),
  ('f-headphones-that-tangle-in-a-pocket', 'Headphones that tangle in a pocket', 'Auriculares que se enredan en el bolsillo'),
  ('f-looking-at-something-through-a-magnifying-glass', 'Looking at something through a magnifying glass', 'Mirar algo con una lupa'),
  ('f-fresh-flowers-on-the-table', 'Fresh flowers on the table', 'Flores frescas en la mesa'),
  ('f-a-wooden-floor-that-creaks', 'A wooden floor that creaks', 'Un suelo de madera que cruje'),
  ('f-a-puzzle-with-one-piece-missing', 'A puzzle with one piece missing', 'Un rompecabezas al que le falta una pieza'),
  ('f-soft-thick-towels', 'Soft thick towels', 'Toallas gruesas y suaves'),
  ('f-an-empty-suitcase-before-a-trip', 'An empty suitcase before a trip', 'Una maleta vacía antes de un viaje'),
  ('f-a-pillow-that-is-far-too-small', 'A pillow that is far too small', 'Una almohada demasiado pequeña'),
  ('f-a-drink-with-too-much-ice', 'A drink with too much ice', 'Una bebida con demasiado hielo'),
  ('f-sticky-tape-that-folds-onto-itself', 'Sticky tape that folds onto itself', 'Cinta adhesiva que se pega sobre sí misma'),
  ('f-a-kettle-that-whistles', 'A kettle that whistles', 'Una tetera que silba'),
  ('f-a-drawer-full-of-old-cables', 'A drawer full of old cables', 'Un cajón lleno de cables viejos'),
  ('f-trousers-worn-until-they-are-soft', 'Trousers worn until they are soft', 'Pantalones usados hasta quedar suaves'),
  ('f-a-letter-written-by-hand', 'A letter written by hand', 'Una carta escrita a mano'),
  ('f-the-bell-on-a-bicycle', 'The bell on a bicycle', 'El timbre de una bicicleta'),
  ('f-a-small-key-nobody-can-identify', 'A small key nobody can identify', 'Una llave pequeña que nadie identifica'),
  ('f-a-blanket-straight-out-of-the-dryer', 'A blanket straight out of the dryer', 'Una manta recién salida de la secadora'),
  ('f-a-chair-that-spins-all-the-way-round', 'A chair that spins all the way round', 'Una silla que gira sin parar'),
  ('f-a-watch-that-is-five-minutes-fast', 'A watch that is five minutes fast', 'Un reloj cinco minutos adelantado'),
  ('f-a-bag-with-far-too-many-pockets', 'A bag with far too many pockets', 'Un bolso con demasiados bolsillos'),
  ('f-a-mirror-in-bad-lighting', 'A mirror in bad lighting', 'Un espejo con mala luz'),
  ('f-a-very-old-cooking-pot', 'A very old cooking pot', 'Una olla de cocina muy vieja'),
  ('f-rainy-afternoons', 'Rainy afternoons', 'Tardes lluviosas'),
  ('f-the-smell-of-rain-on-dry-ground', 'The smell of rain on dry ground', 'El olor de la lluvia sobre tierra seca'),
  ('f-waking-up-before-the-alarm', 'Waking up before the alarm', 'Despertarse antes del despertador'),
  ('f-a-very-long-hug', 'A very long hug', 'Un abrazo muy largo'),
  ('f-cold-feet-in-a-warm-bed', 'Cold feet in a warm bed', 'Pies fríos en una cama caliente'),
  ('f-finding-money-in-an-old-coat', 'Finding money in an old coat', 'Encontrar dinero en un abrigo viejo'),
  ('f-the-first-day-of-the-holidays', 'The first day of the holidays', 'El primer día de vacaciones'),
  ('f-a-haircut-nobody-asked-for', 'A haircut nobody asked for', 'Un corte de pelo que nadie pidió'),
  ('f-applause-after-you-finish-speaking', 'Applause after you finish speaking', 'Aplausos cuando terminas de hablar'),
  ('f-a-crowded-bus-in-summer', 'A crowded bus in summer', 'Un autobús lleno en verano'),
  ('f-sitting-in-the-dentist-s-waiting-room', 'Sitting in the dentist''s waiting room', 'Estar en la sala de espera del dentista'),
  ('f-a-power-cut-at-night', 'A power cut at night', 'Un apagón por la noche'),
  ('f-silence-in-a-very-big-house', 'Silence in a very big house', 'El silencio en una casa muy grande'),
  ('f-sand-inside-your-shoes', 'Sand inside your shoes', 'Arena dentro de los zapatos'),
  ('f-sunburn-on-your-shoulders', 'Sunburn on your shoulders', 'Quemadura de sol en los hombros'),
  ('f-a-stranger-holding-the-door-for-you', 'A stranger holding the door for you', 'Un desconocido que te sujeta la puerta'),
  ('f-losing-your-page-in-a-book', 'Losing your page in a book', 'Perder la página de un libro'),
  ('f-waking-up-in-an-unfamiliar-room', 'Waking up in an unfamiliar room', 'Despertar en una habitación desconocida'),
  ('f-snow-on-a-quiet-street', 'Snow on a quiet street', 'Nieve en una calle tranquila'),
  ('f-fireworks-heard-from-far-away', 'Fireworks heard from far away', 'Fuegos artificiales oídos de lejos'),
  ('f-being-caught-in-the-rain-with-no-coat', 'Being caught in the rain with no coat', 'Que te pille la lluvia sin abrigo'),
  ('f-the-last-day-of-the-school-year', 'The last day of the school year', 'El último día del curso escolar'),
  ('f-someone-singing-out-of-tune', 'Someone singing out of tune', 'Alguien cantando desafinado'),
  ('f-a-baby-laughing', 'A baby laughing', 'Un bebé riéndose'),
  ('f-standing-in-a-very-long-queue', 'Standing in a very long queue', 'Estar en una cola larguísima'),
  ('f-wind-on-a-warm-evening', 'Wind on a warm evening', 'Viento en una tarde cálida'),
  ('f-bare-feet-on-cool-grass', 'Bare feet on cool grass', 'Pies descalzos sobre hierba fresca'),
  ('f-the-sound-of-a-distant-train', 'The sound of a distant train', 'El sonido de un tren lejano'),
  ('f-an-unexpected-visit', 'An unexpected visit', 'Una visita inesperada'),
  ('f-the-smell-of-coffee-in-the-morning', 'The smell of coffee in the morning', 'El olor a café por la mañana'),
  ('f-falling-asleep-on-a-long-journey', 'Falling asleep on a long journey', 'Quedarse dormido en un viaje largo'),
  ('f-being-the-first-person-to-arrive', 'Being the first person to arrive', 'Ser la primera persona en llegar'),
  ('f-being-the-last-person-to-leave', 'Being the last person to leave', 'Ser la última persona en irse'),
  ('f-a-very-slow-lift', 'A very slow lift', 'Un ascensor muy lento'),
  ('f-cold-water-on-a-hot-face', 'Cold water on a hot face', 'Agua fría en una cara acalorada'),
  ('f-losing-a-game-that-you-chose', 'Losing a game that you chose', 'Perder un juego que tú elegiste'),
  ('f-having-to-explain-a-joke-twice', 'Having to explain a joke twice', 'Tener que explicar un chiste dos veces'),
  ('f-remembering-a-name-just-in-time', 'Remembering a name just in time', 'Recordar un nombre justo a tiempo'),
  ('f-forgetting-why-you-walked-into-a-room', 'Forgetting why you walked into a room', 'Olvidar por qué entraste a una habitación'),
  ('f-a-neighbour-playing-loud-music', 'A neighbour playing loud music', 'Un vecino con la música muy alta'),
  ('f-a-parcel-arriving-earlier-than-promised', 'A parcel arriving earlier than promised', 'Un paquete que llega antes de lo prometido'),
  ('f-missing-a-step-on-the-stairs', 'Missing a step on the stairs', 'Fallar un escalón en las escaleras'),
  ('f-hearing-a-recording-of-your-own-voice', 'Hearing a recording of your own voice', 'Oír una grabación de tu propia voz'),
  ('f-a-dog-that-wants-to-play', 'A dog that wants to play', 'Un perro que quiere jugar'),
  ('f-a-cat-that-sits-on-your-lap', 'A cat that sits on your lap', 'Un gato que se sienta en tu regazo'),
  ('f-thunder-in-the-middle-of-the-night', 'Thunder in the middle of the night', 'Truenos en plena noche'),
  ('f-stepping-into-a-warm-shower', 'Stepping into a warm shower', 'Meterse en una ducha caliente'),
  ('f-the-moment-a-film-starts', 'The moment a film starts', 'El momento en que empieza una película'),
  ('f-waiting-for-a-train-that-is-late', 'Waiting for a train that is late', 'Esperar un tren que llega tarde'),
  ('f-assembling-a-gift-at-midnight', 'Assembling a gift at midnight', 'Montar un regalo a medianoche'),
  ('f-a-family-photo-that-takes-twenty-minutes', 'A family photo that takes twenty minutes', 'Una foto de familia que tarda veinte minutos'),
  ('f-choosing-a-film-that-everyone-accepts', 'Choosing a film that everyone accepts', 'Elegir una película que todos acepten'),
  ('f-splitting-a-bill-many-ways', 'Splitting a bill many ways', 'Dividir una cuenta entre muchos'),
  ('f-moving-to-a-new-house', 'Moving to a new house', 'Mudarse a una casa nueva'),
  ('f-a-meeting-that-could-have-been-a-message', 'A meeting that could have been a message', 'Una reunión que podría haber sido un mensaje'),
  ('f-losing-your-keys-inside-your-own-house', 'Losing your keys inside your own house', 'Perder las llaves dentro de tu propia casa'),
  ('f-parking-in-a-very-tight-space', 'Parking in a very tight space', 'Aparcar en un hueco muy estrecho'),
  ('f-washing-dishes-as-a-team', 'Washing dishes as a team', 'Lavar los platos en equipo'),
  ('f-waiting-for-dough-to-rise', 'Waiting for dough to rise', 'Esperar a que suba la masa'),
  ('f-small-talk-with-a-taxi-driver', 'Small talk with a taxi driver', 'Conversación breve con un taxista'),
  ('f-reading-the-instructions-after-failing', 'Reading the instructions after failing', 'Leer las instrucciones después de fallar'),
  ('f-arriving-at-the-airport-far-too-early', 'Arriving at the airport far too early', 'Llegar al aeropuerto demasiado temprano'),
  ('f-letting-someone-else-drive-your-car', 'Letting someone else drive your car', 'Dejar que otra persona conduzca tu coche'),
  ('f-wrapping-a-lot-of-presents', 'Wrapping a lot of presents', 'Envolver muchos regalos'),
  ('f-a-group-deciding-where-to-eat', 'A group deciding where to eat', 'Un grupo decidiendo dónde comer'),
  ('f-choosing-a-name-for-a-pet', 'Choosing a name for a pet', 'Elegir el nombre de una mascota'),
  ('f-sharing-one-bathroom-with-many-people', 'Sharing one bathroom with many people', 'Compartir un solo baño con mucha gente'),
  ('f-tidying-up-after-a-party', 'Tidying up after a party', 'Ordenar después de una fiesta'),
  ('f-sitting-in-the-middle-seat', 'Sitting in the middle seat', 'Ir sentado en el asiento del medio'),
  ('f-being-asked-to-help-move-a-sofa', 'Being asked to help move a sofa', 'Que te pidan ayuda para mover un sofá'),
  ('f-trying-to-whisper-in-a-cinema', 'Trying to whisper in a cinema', 'Intentar susurrar en el cine'),
  ('f-guessing-a-password-you-forgot', 'Guessing a password you forgot', 'Adivinar una contraseña que olvidaste'),
  ('f-losing-at-cards-to-a-child', 'Losing at cards to a child', 'Perder a las cartas contra un niño'),
  ('f-waiting-for-water-to-boil', 'Waiting for water to boil', 'Esperar a que hierva el agua'),
  ('f-folding-a-fitted-bed-sheet', 'Folding a fitted bed sheet', 'Doblar una sábana ajustable'),
  ('f-writing-a-shopping-list', 'Writing a shopping list', 'Escribir la lista de la compra'),
  ('f-choosing-the-slowest-queue', 'Choosing the slowest queue', 'Elegir la cola más lenta'),
  ('f-talking-to-a-house-plant', 'Talking to a house plant', 'Hablarle a una planta de casa'),
  ('f-cutting-your-own-hair', 'Cutting your own hair', 'Cortarte el pelo tú mismo'),
  ('f-trying-to-be-quiet-in-a-creaky-house', 'Trying to be quiet in a creaky house', 'Intentar no hacer ruido en una casa que cruje'),
  ('f-rearranging-all-the-living-room-furniture', 'Rearranging all the living room furniture', 'Reorganizar todos los muebles del salón'),
  ('f-looking-after-someone-else-s-cat', 'Looking after someone else''s cat', 'Cuidar el gato de otra persona'),
  ('f-sending-a-message-to-the-wrong-person', 'Sending a message to the wrong person', 'Enviar un mensaje a la persona equivocada'),
  ('f-a-group-photo-where-someone-blinks', 'A group photo where someone blinks', 'Una foto de grupo en la que alguien parpadea'),
  ('f-explaining-a-phone-to-a-relative', 'Explaining a phone to a relative', 'Explicar un teléfono a un familiar'),
  ('f-waiting-for-a-table-at-a-restaurant', 'Waiting for a table at a restaurant', 'Esperar mesa en un restaurante'),
  ('f-dressing-for-weather-that-keeps-changing', 'Dressing for weather that keeps changing', 'Vestirse para un tiempo que cambia sin parar'),
  ('f-a-birthday-that-falls-on-a-monday', 'A birthday that falls on a Monday', 'Un cumpleaños que cae en lunes'),
  ('f-sharing-one-umbrella-between-two-people', 'Sharing one umbrella between two people', 'Compartir un paraguas entre dos personas'),
  ('f-a-tower-of-clean-laundry-on-a-chair', 'A tower of clean laundry on a chair', 'Una torre de ropa limpia sobre una silla'),
  ('f-being-on-time-when-nobody-else-is', 'Being on time when nobody else is', 'Ser puntual cuando nadie más lo es'),
  ('f-answering-the-phone-half-asleep', 'Answering the phone half asleep', 'Contestar el teléfono medio dormido'),
  ('f-being-taught-a-game-badly', 'Being taught a game badly', 'Que te expliquen mal un juego'),
  ('f-queueing-to-get-out-of-a-car-park', 'Queueing to get out of a car park', 'Hacer cola para salir de un aparcamiento'),
  ('f-trying-to-fold-a-paper-map-again', 'Trying to fold a paper map again', 'Intentar volver a doblar un mapa de papel'),
  ('f-early-mornings', 'Early mornings', 'Las mañanas muy temprano'),
  ('f-very-cold-weather', 'Very cold weather', 'El frío intenso'),
  ('f-complete-silence', 'Complete silence', 'El silencio completo'),
  ('f-surprises', 'Surprises', 'Las sorpresas'),
  ('f-long-goodbyes', 'Long goodbyes', 'Las despedidas largas'),
  ('f-making-plans-months-in-advance', 'Making plans months in advance', 'Hacer planes con meses de antelación'),
  ('f-changing-plans-at-the-last-minute', 'Changing plans at the last minute', 'Cambiar de planes a última hora'),
  ('f-very-large-crowds', 'Very large crowds', 'Las multitudes muy grandes'),
  ('f-polite-conversation-with-strangers', 'Polite conversation with strangers', 'La conversación cortés con desconocidos'),
  ('f-being-the-centre-of-attention', 'Being the centre of attention', 'Ser el centro de atención'),
  ('f-winning-by-a-huge-margin', 'Winning by a huge margin', 'Ganar por una diferencia enorme'),
  ('f-winning-by-a-single-point', 'Winning by a single point', 'Ganar por un solo punto'),
  ('f-rules-read-aloud-before-playing', 'Rules read aloud before playing', 'Reglas leídas en voz alta antes de jugar'),
  ('f-waiting-for-your-turn', 'Waiting for your turn', 'Esperar tu turno'),
  ('f-eating-from-one-shared-plate', 'Eating from one shared plate', 'Comer de un plato compartido'),
  ('f-sleeping-with-the-window-open', 'Sleeping with the window open', 'Dormir con la ventana abierta'),
  ('f-loud-thunderstorms', 'Loud thunderstorms', 'Las tormentas ruidosas'),
  ('f-films-that-last-three-hours', 'Films that last three hours', 'Las películas de tres horas'),
  ('f-doing-something-for-the-very-first-time', 'Doing something for the very first time', 'Hacer algo por primera vez'),
  ('f-doing-absolutely-nothing', 'Doing absolutely nothing', 'No hacer absolutamente nada'),
  ('f-keeping-a-secret-for-a-long-time', 'Keeping a secret for a long time', 'Guardar un secreto mucho tiempo'),
  ('f-being-right-about-something-small', 'Being right about something small', 'Tener razón en algo pequeño'),
  ('f-clothes-folded-very-neatly', 'Clothes folded very neatly', 'Ropa doblada con mucho esmero'),
  ('f-speaking-in-front-of-a-group', 'Speaking in front of a group', 'Hablar delante de un grupo'),
  ('f-bright-fluorescent-lighting', 'Bright fluorescent lighting', 'La luz fluorescente brillante'),
  ('f-gifts-made-by-hand', 'Gifts made by hand', 'Los regalos hechos a mano'),
  ('f-being-exactly-on-time', 'Being exactly on time', 'Llegar exactamente a la hora'),
  ('f-sleeping-late-on-a-free-day', 'Sleeping late on a free day', 'Dormir hasta tarde en un día libre'),
  ('f-being-asked-for-your-opinion', 'Being asked for your opinion', 'Que te pidan tu opinión'),
  ('f-loud-family-dinners', 'Loud family dinners', 'Las cenas familiares ruidosas'),
  ('f-very-quiet-libraries', 'Very quiet libraries', 'Las bibliotecas muy silenciosas'),
  ('f-second-chances', 'Second chances', 'Las segundas oportunidades'),
  ('f-wearing-shoes-indoors', 'Wearing shoes indoors', 'Llevar zapatos dentro de casa'),
  ('f-hot-weather-at-night', 'Hot weather at night', 'El calor por la noche'),
  ('f-people-talking-during-a-film', 'People talking during a film', 'Gente hablando durante una película'),
  ('f-lists-organised-by-colour', 'Lists organised by colour', 'Las listas organizadas por color'),
  ('f-decisions-made-by-a-group', 'Decisions made by a group', 'Las decisiones tomadas en grupo'),
  ('f-old-songs-you-know-by-heart', 'Old songs you know by heart', 'Canciones viejas que te sabes de memoria'),
  ('f-brand-new-shoes', 'Brand new shoes', 'Los zapatos recién estrenados'),
  ('f-advice-you-did-not-ask-for', 'Advice you did not ask for', 'Los consejos que no pediste'),
  ('f-slow-walkers-directly-in-front-of-you', 'Slow walkers directly in front of you', 'Gente que camina despacio justo delante de ti'),
  ('f-sitting-next-to-a-window', 'Sitting next to a window', 'Sentarse junto a una ventana'),
  ('f-wrapping-paper-that-tears-too-easily', 'Wrapping paper that tears too easily', 'Papel de regalo que se rompe con facilidad'),
  ('f-taking-the-last-piece', 'Taking the last piece', 'Llevarse el último trozo'),
  ('f-rainbows', 'Rainbows', 'Los arcoíris'),
  ('f-odd-numbers', 'Odd numbers', 'Los números impares'),
  ('f-long-car-journeys', 'Long car journeys', 'Los viajes largos en coche'),
  ('f-being-told-a-story-you-already-know', 'Being told a story you already know', 'Que te cuenten una historia que ya conoces'),
  ('f-handwriting-you-can-actually-read', 'Handwriting you can actually read', 'Una letra que de verdad se puede leer'),
  ('f-a-day-with-nothing-planned', 'A day with nothing planned', 'Un día sin nada planeado'),
  ('f-costumes-at-a-party', 'Costumes at a party', 'Los disfraces en una fiesta'),
  ('f-photographs-taken-without-warning', 'Photographs taken without warning', 'Las fotos tomadas sin avisar'),
  ('f-waking-up-to-sunshine', 'Waking up to sunshine', 'Despertar con el sol entrando'),
  ('f-a-house-full-of-visitors', 'A house full of visitors', 'Una casa llena de visitas'),
  ('f-working-while-music-plays', 'Working while music plays', 'Trabajar con música puesta')
on conflict (id) do update
  set text_en = excluded.text_en,
      text_es = excluded.text_es;
