-- ============================================================================
-- Sort It Out — factory card dictionary seed (generated file, do not edit by hand)
--
-- Source:    supabase/seed/factory_cards.json
-- Regenerate: pnpm seed:factory
-- Cards:     399
--
-- Every factory card is original to this project and carries both an English and a
-- Spanish rendering of the same canonical concept.
-- ============================================================================

insert into public.factory_cards (id, text_en, text_es) values
  ('f-tofu', 'Tofu', 'Tofu'),
  ('f-sparkling-water', 'Sparkling water', 'Agua con gas'),
  ('f-pickles', 'Pickles', 'Pepinillos'),
  ('f-candy', 'Candy', 'Golosinas'),
  ('f-pineapple-on-pizza', 'Pineapple on pizza', 'Pizza con piña'),
  ('f-olives', 'Olives', 'Aceitunas'),
  ('f-sushi', 'Sushi', 'Sushi'),
  ('f-spicy-food', 'Spicy food', 'Comida picante'),
  ('f-dark-chocolate', 'Dark chocolate', 'Chocolate negro'),
  ('f-coffee', 'Coffee', 'Café'),
  ('f-tea', 'Tea', 'Té'),
  ('f-energy-drinks', 'Energy drinks', 'Bebidas energéticas'),
  ('f-avocados', 'Avocados', 'Aguacates'),
  ('f-broccoli', 'Broccoli', 'Brócoli'),
  ('f-mushrooms', 'Mushrooms', 'Setas'),
  ('f-vegan-cheese', 'Vegan cheese', 'Queso vegano'),
  ('f-street-food', 'Street food', 'Comida callejera'),
  ('f-fast-food', 'Fast food', 'Comida rápida'),
  ('f-homemade-bread', 'Homemade bread', 'Pan casero'),
  ('f-breakfast', 'Breakfast', 'Desayuno'),
  ('f-brunch', 'Brunch', 'Brunch'),
  ('f-buffets', 'Buffets', 'Bufés'),
  ('f-picnics', 'Picnics', 'Picnics'),
  ('f-leftovers', 'Leftovers', 'Sobras'),
  ('f-soup', 'Soup', 'Sopa'),
  ('f-salad', 'Salad', 'Ensalada'),
  ('f-ice-cream', 'Ice cream', 'Helado'),
  ('f-cheesecake', 'Cheesecake', 'Tarta de queso'),
  ('f-churros', 'Churros', 'Churros'),
  ('f-popcorn', 'Popcorn', 'Palomitas'),
  ('f-licorice', 'Licorice', 'Regaliz'),
  ('f-mint-chocolate', 'Mint chocolate', 'Chocolate con menta'),
  ('f-ketchup', 'Ketchup', 'Kétchup'),
  ('f-mayonnaise', 'Mayonnaise', 'Mayonesa'),
  ('f-garlic', 'Garlic', 'Ajo'),
  ('f-coriander', 'Coriander', 'Cilantro'),
  ('f-hot-sauce', 'Hot sauce', 'Salsa picante'),
  ('f-oat-milk', 'Oat milk', 'Leche de avena'),
  ('f-coconut', 'Coconut', 'Coco'),
  ('f-bananas', 'Bananas', 'Plátanos'),
  ('f-seafood', 'Seafood', 'Marisco'),
  ('f-raw-onions', 'Raw onions', 'Cebolla cruda'),
  ('f-raisins', 'Raisins', 'Pasas'),
  ('f-french-fries', 'French fries', 'Patatas fritas'),
  ('f-pizza', 'Pizza', 'Pizza'),
  ('f-cooking', 'Cooking', 'Cocinar'),
  ('f-reading', 'Reading', 'Leer'),
  ('f-horror-movies', 'Horror movies', 'Películas de terror'),
  ('f-memes', 'Memes', 'Memes'),
  ('f-comedians', 'Comedians', 'Humoristas'),
  ('f-cute-animal-videos', 'Cute animal videos', 'Vídeos de animales adorables'),
  ('f-asmr-videos', 'ASMR videos', 'Vídeos de ASMR'),
  ('f-fanfiction', 'Fanfiction', 'Fanfiction'),
  ('f-card-games', 'Card games', 'Juegos de cartas'),
  ('f-board-games', 'Board games', 'Juegos de mesa'),
  ('f-video-games', 'Video games', 'Videojuegos'),
  ('f-karaoke', 'Karaoke', 'Karaoke'),
  ('f-dancing', 'Dancing', 'Bailar'),
  ('f-singing', 'Singing', 'Cantar'),
  ('f-drawing', 'Drawing', 'Dibujar'),
  ('f-painting', 'Painting', 'Pintar'),
  ('f-photography', 'Photography', 'Fotografía'),
  ('f-pottery', 'Pottery', 'Cerámica'),
  ('f-gardening', 'Gardening', 'Jardinería'),
  ('f-knitting', 'Knitting', 'Tejer'),
  ('f-jigsaw-puzzles', 'Jigsaw puzzles', 'Puzles'),
  ('f-crosswords', 'Crosswords', 'Crucigramas'),
  ('f-podcasts', 'Podcasts', 'Pódcasts'),
  ('f-audiobooks', 'Audiobooks', 'Audiolibros'),
  ('f-reality-tv', 'Reality TV', 'Reality shows'),
  ('f-documentaries', 'Documentaries', 'Documentales'),
  ('f-anime', 'Anime', 'Anime'),
  ('f-musicals', 'Musicals', 'Musicales'),
  ('f-superhero-movies', 'Superhero movies', 'Películas de superhéroes'),
  ('f-true-crime', 'True crime', 'Crímenes reales'),
  ('f-science-fiction', 'Science fiction', 'Ciencia ficción'),
  ('f-romance-novels', 'Romance novels', 'Novelas románticas'),
  ('f-poetry', 'Poetry', 'Poesía'),
  ('f-live-music', 'Live music', 'Música en directo'),
  ('f-music-festivals', 'Music festivals', 'Festivales de música'),
  ('f-museums', 'Museums', 'Museos'),
  ('f-theatre', 'Theatre', 'Teatro'),
  ('f-stand-up-comedy', 'Stand-up comedy', 'Monólogos de humor'),
  ('f-magic-tricks', 'Magic tricks', 'Trucos de magia'),
  ('f-astrology', 'Astrology', 'Astrología'),
  ('f-conspiracy-theories', 'Conspiracy theories', 'Teorías de la conspiración'),
  ('f-tarot-cards', 'Tarot cards', 'Cartas del tarot'),
  ('f-collecting-things', 'Collecting things', 'Coleccionar cosas'),
  ('f-journaling', 'Journaling', 'Escribir un diario'),
  ('f-creative-writing', 'Creative writing', 'Escritura creativa'),
  ('f-learning-languages', 'Learning languages', 'Aprender idiomas'),
  ('f-chess', 'Chess', 'Ajedrez'),
  ('f-escape-rooms', 'Escape rooms', 'Escape rooms'),
  ('f-trivia-nights', 'Trivia nights', 'Noches de preguntas'),
  ('f-diy-projects', 'DIY projects', 'Proyectos de bricolaje'),
  ('f-cats', 'Cats', 'Gatos'),
  ('f-dogs', 'Dogs', 'Perros'),
  ('f-animals', 'Animals', 'Animales'),
  ('f-pigeons', 'Pigeons', 'Palomas'),
  ('f-spiders', 'Spiders', 'Arañas'),
  ('f-snakes', 'Snakes', 'Serpientes'),
  ('f-sharks', 'Sharks', 'Tiburones'),
  ('f-dolphins', 'Dolphins', 'Delfines'),
  ('f-horses', 'Horses', 'Caballos'),
  ('f-cows', 'Cows', 'Vacas'),
  ('f-goats', 'Goats', 'Cabras'),
  ('f-insects', 'Insects', 'Insectos'),
  ('f-zoos', 'Zoos', 'Zoológicos'),
  ('f-aquariums', 'Aquariums', 'Acuarios'),
  ('f-houseplants', 'Houseplants', 'Plantas de interior'),
  ('f-flowers', 'Flowers', 'Flores'),
  ('f-forests', 'Forests', 'Bosques'),
  ('f-beaches', 'Beaches', 'Playas'),
  ('f-mountains', 'Mountains', 'Montañas'),
  ('f-the-desert', 'The desert', 'El desierto'),
  ('f-snow', 'Snow', 'Nieve'),
  ('f-rain', 'Rain', 'Lluvia'),
  ('f-thunderstorms', 'Thunderstorms', 'Tormentas'),
  ('f-sunny-days', 'Sunny days', 'Días soleados'),
  ('f-sunsets', 'Sunsets', 'Atardeceres'),
  ('f-camping', 'Camping', 'Acampar'),
  ('f-hiking', 'Hiking', 'Senderismo'),
  ('f-swimming', 'Swimming', 'Nadar'),
  ('f-birdwatching', 'Birdwatching', 'Observar aves'),
  ('f-stargazing', 'Stargazing', 'Mirar las estrellas'),
  ('f-procrastinating', 'Procrastinating', 'Procrastinar'),
  ('f-waking-up-early', 'Waking up early', 'Madrugar'),
  ('f-naps', 'Naps', 'Siestas'),
  ('f-sleeping-in', 'Sleeping in', 'Dormir hasta tarde'),
  ('f-working-out', 'Working out', 'Hacer ejercicio'),
  ('f-running', 'Running', 'Correr'),
  ('f-yoga', 'Yoga', 'Yoga'),
  ('f-pilates', 'Pilates', 'Pilates'),
  ('f-martial-arts', 'Martial arts', 'Artes marciales'),
  ('f-football', 'Football', 'Fútbol'),
  ('f-basketball', 'Basketball', 'Baloncesto'),
  ('f-tennis', 'Tennis', 'Tenis'),
  ('f-bicycles', 'Bicycles', 'Bicicletas'),
  ('f-motorbikes', 'Motorbikes', 'Motos'),
  ('f-road-trips', 'Road trips', 'Viajes por carretera'),
  ('f-flying', 'Flying', 'Volar'),
  ('f-train-journeys', 'Train journeys', 'Viajes en tren'),
  ('f-public-transport', 'Public transport', 'Transporte público'),
  ('f-driving', 'Driving', 'Conducir'),
  ('f-walking', 'Walking', 'Caminar'),
  ('f-shopping', 'Shopping', 'Ir de compras'),
  ('f-thrifting', 'Thrifting', 'Comprar de segunda mano'),
  ('f-fashion', 'Fashion', 'Moda'),
  ('f-makeup', 'Makeup', 'Maquillaje'),
  ('f-tattoos', 'Tattoos', 'Tatuajes'),
  ('f-piercings', 'Piercings', 'Piercings'),
  ('f-funny-t-shirts', 'Funny T-shirts', 'Camisetas graciosas'),
  ('f-high-heels', 'High heels', 'Tacones'),
  ('f-uniforms', 'Uniforms', 'Uniformes'),
  ('f-pajamas', 'Pajamas', 'Pijamas'),
  ('f-minimalism', 'Minimalism', 'Minimalismo'),
  ('f-veganism', 'Veganism', 'Veganismo'),
  ('f-meditation', 'Meditation', 'Meditación'),
  ('f-cleaning', 'Cleaning', 'Limpiar'),
  ('f-tidying-up', 'Tidying up', 'Ordenar la casa'),
  ('f-baking', 'Baking', 'Hornear'),
  ('f-online-shopping', 'Online shopping', 'Compras por internet'),
  ('f-home-workouts', 'Home workouts', 'Ejercicio en casa'),
  ('f-team-sports', 'Team sports', 'Deportes de equipo'),
  ('f-extreme-sports', 'Extreme sports', 'Deportes extremos'),
  ('f-family-gatherings', 'Family gatherings', 'Reuniones familiares'),
  ('f-birthdays', 'Birthdays', 'Cumpleaños'),
  ('f-weddings', 'Weddings', 'Bodas'),
  ('f-office-parties', 'Office parties', 'Fiestas de empresa'),
  ('f-surprise-parties', 'Surprise parties', 'Fiestas sorpresa'),
  ('f-small-talk', 'Small talk', 'Conversaciones triviales'),
  ('f-gossip', 'Gossip', 'Cotilleos'),
  ('f-group-chats', 'Group chats', 'Chats de grupo'),
  ('f-voice-messages', 'Voice messages', 'Mensajes de voz'),
  ('f-video-calls', 'Video calls', 'Videollamadas'),
  ('f-phone-calls', 'Phone calls', 'Llamadas telefónicas'),
  ('f-texting', 'Texting', 'Mensajear'),
  ('f-social-media', 'Social media', 'Redes sociales'),
  ('f-influencers', 'Influencers', 'Influencers'),
  ('f-online-dating', 'Online dating', 'Citas por internet'),
  ('f-blind-dates', 'Blind dates', 'Citas a ciegas'),
  ('f-first-dates', 'First dates', 'Primeras citas'),
  ('f-long-distance-relationships', 'Long-distance relationships', 'Relaciones a distancia'),
  ('f-public-speaking', 'Public speaking', 'Hablar en público'),
  ('f-networking', 'Networking', 'Hacer contactos'),
  ('f-teamwork', 'Teamwork', 'Trabajo en equipo'),
  ('f-competition', 'Competition', 'Competición'),
  ('f-money', 'Money', 'Dinero'),
  ('f-saving-money', 'Saving money', 'Ahorrar dinero'),
  ('f-spending-money', 'Spending money', 'Gastar dinero'),
  ('f-being-late', 'Being late', 'Llegar tarde'),
  ('f-punctuality', 'Punctuality', 'Puntualidad'),
  ('f-queuing', 'Queuing', 'Hacer cola'),
  ('f-sharing-food', 'Sharing food', 'Compartir comida'),
  ('f-giving-gifts', 'Giving gifts', 'Hacer regalos'),
  ('f-receiving-gifts', 'Receiving gifts', 'Recibir regalos'),
  ('f-compliments', 'Compliments', 'Cumplidos'),
  ('f-advice', 'Advice', 'Consejos'),
  ('f-apologies', 'Apologies', 'Disculpas'),
  ('f-secrets', 'Secrets', 'Secretos'),
  ('f-traditions', 'Traditions', 'Tradiciones'),
  ('f-rules', 'Rules', 'Reglas'),
  ('f-routines', 'Routines', 'Rutinas'),
  ('f-spontaneity', 'Spontaneity', 'Espontaneidad'),
  ('f-planning', 'Planning', 'Planificar'),
  ('f-mondays', 'Mondays', 'Lunes'),
  ('f-weekends', 'Weekends', 'Fines de semana'),
  ('f-holidays', 'Holidays', 'Vacaciones'),
  ('f-christmas', 'Christmas', 'Navidad'),
  ('f-new-year-s-eve', 'New Year''s Eve', 'Nochevieja'),
  ('f-valentine-s-day', 'Valentine''s Day', 'San Valentín'),
  ('f-halloween', 'Halloween', 'Halloween'),
  ('f-neighbours', 'Neighbours', 'Vecinos'),
  ('f-children', 'Children', 'Niños'),
  ('f-babies', 'Babies', 'Bebés'),
  ('f-libraries', 'Libraries', 'Bibliotecas'),
  ('f-airports', 'Airports', 'Aeropuertos'),
  ('f-supermarkets', 'Supermarkets', 'Supermercados'),
  ('f-shopping-centres', 'Shopping centres', 'Centros comerciales'),
  ('f-restaurants', 'Restaurants', 'Restaurantes'),
  ('f-cafes', 'Cafés', 'Cafeterías'),
  ('f-nightclubs', 'Nightclubs', 'Discotecas'),
  ('f-theme-parks', 'Theme parks', 'Parques temáticos'),
  ('f-school', 'School', 'El colegio'),
  ('f-university', 'University', 'La universidad'),
  ('f-offices', 'Offices', 'Oficinas'),
  ('f-remote-work', 'Remote work', 'Teletrabajo'),
  ('f-big-cities', 'Big cities', 'Grandes ciudades'),
  ('f-villages', 'Villages', 'Pueblos'),
  ('f-islands', 'Islands', 'Islas'),
  ('f-hotels', 'Hotels', 'Hoteles'),
  ('f-hostels', 'Hostels', 'Hostales'),
  ('f-smartphones', 'Smartphones', 'Teléfonos inteligentes'),
  ('f-smartwatches', 'Smartwatches', 'Relojes inteligentes'),
  ('f-robots', 'Robots', 'Robots'),
  ('f-artificial-intelligence', 'Artificial intelligence', 'Inteligencia artificial'),
  ('f-emojis', 'Emojis', 'Emojis'),
  ('f-selfies', 'Selfies', 'Selfis'),
  ('f-photo-filters', 'Photo filters', 'Filtros de fotos'),
  ('f-advertisements', 'Advertisements', 'Anuncios'),
  ('f-passwords', 'Passwords', 'Contraseñas'),
  ('f-cash', 'Cash', 'Dinero en efectivo'),
  ('f-credit-cards', 'Credit cards', 'Tarjetas de crédito'),
  ('f-second-hand-clothes', 'Second-hand clothes', 'Ropa de segunda mano'),
  ('f-luxury-brands', 'Luxury brands', 'Marcas de lujo'),
  ('f-plastic-surgery', 'Plastic surgery', 'Cirugía estética'),
  ('f-fame', 'Fame', 'Fama'),
  ('f-luck', 'Luck', 'Suerte'),
  ('f-nostalgia', 'Nostalgia', 'Nostalgia'),
  ('f-silence', 'Silence', 'Silencio'),
  ('f-noise', 'Noise', 'Ruido'),
  ('f-listening-to-the-radio', 'Listening to the radio', 'Escuchar la radio'),
  ('f-spotify-playlists', 'Spotify playlists', 'Listas de reproducción de Spotify'),
  ('f-darkness', 'Darkness', 'Oscuridad'),
  ('f-cold-weather', 'Cold weather', 'El frío'),
  ('f-hot-weather', 'Hot weather', 'El calor'),
  ('f-mornings', 'Mornings', 'Mañanas'),
  ('f-midnight', 'Midnight', 'Medianoche'),
  ('f-aliens', 'Aliens', 'Extraterrestres'),
  ('f-ghosts', 'Ghosts', 'Fantasmas'),
  ('f-good-manners', 'Good manners', 'Buena educación'),
  ('f-sending-emails', 'Sending emails', 'Mandar emails'),
  ('f-polite-conversation', 'Polite conversation', 'Conversación educada'),
  ('f-romantic-movies', 'Romantic movies', 'Películas románticas'),
  ('f-politics', 'Politics', 'Política'),
  ('f-watching-sports', 'Watching sports', 'Ver deportes'),
  ('f-going-to-the-cinema', 'Going to the cinema', 'Ir al cine'),
  ('f-twitter', 'Twitter', 'Twitter'),
  ('f-talent-shows', 'Talent shows', 'Concursos de talentos'),
  ('f-dad-jokes', 'Dad jokes', 'Chistes de padre'),
  ('f-your-cousins', 'Your cousins', 'Tus primos'),
  ('f-your-family', 'Your family', 'Tu familia'),
  ('f-your-mother-in-law', 'Your mother-in-law', 'Tu suegra'),
  ('f-lgbtq-rights', 'LGBTQ+ rights', 'Derechos LGBTQ+'),
  ('f-dinosaurs', 'Dinosaurs', 'Dinosaurios'),
  ('f-birds', 'Birds', 'Pájaros'),
  ('f-kangaroos', 'Kangaroos', 'Canguros'),
  ('f-nearby-supermarkets', 'Nearby supermarkets', 'Supermercados cercanos'),
  ('f-quiet-neighbours', 'Quiet neighbours', 'Vecinos silenciosos'),
  ('f-friends', 'Friends', 'Amigos'),
  ('f-mystery-novels', 'Mystery novels', 'Novelas de misterio'),
  ('f-air-fryers', 'Air fryers', 'Freidoras de aire'),
  ('f-sandwiches', 'Sandwiches', 'Sándwiches'),
  ('f-sandwich-makers', 'Sandwich makers', 'Sandwicheras'),
  ('f-waffle-makers', 'Waffle makers', 'Gofreras'),
  ('f-spanish-omelette', 'Spanish omelette', 'Tortilla española'),
  ('f-fuet', 'Fuet', 'Fuet'),
  ('f-croquettes', 'Croquettes', 'Croquetas'),
  ('f-serrano-ham', 'Serrano ham', 'Jamón serrano'),
  ('f-climbing', 'Climbing', 'Escalada'),
  ('f-dressing-up', 'Dressing up', 'Vestirse elegante'),
  ('f-wearing-costumes', 'Wearing costumes', 'Disfrazarse'),
  ('f-drinking-beer', 'Drinking beer', 'Beber cerveza'),
  ('f-climate-change', 'Climate change', 'Cambio climático'),
  ('f-animal-rights', 'Animal rights', 'Derechos de los animales'),
  ('f-freedom-of-speech', 'Freedom of speech', 'Libertad de expresión'),
  ('f-public-healthcare', 'Public healthcare', 'Sanidad pública'),
  ('f-recycling', 'Recycling', 'Reciclaje'),
  ('f-living-alone', 'Living alone', 'Vivir solo'),
  ('f-work-life-balance', 'Work-life balance', 'Equilibrio laboral y personal'),
  ('f-handmade-gifts', 'Handmade gifts', 'Regalos hechos a mano'),
  ('f-event-planning', 'Event planning', 'Organizar eventos'),
  ('f-all-you-can-eat-buffets', 'All-you-can-eat buffets', 'Bufés ilimitados'),
  ('f-hot-dogs', 'Hot dogs', 'Perritos calientes'),
  ('f-new-year-s-day', 'New Year''s Day', 'Año Nuevo'),
  ('f-your-birthday', 'Your birthday', 'Tu cumpleaños'),
  ('f-new-gadgets', 'New gadgets', 'Gadgets nuevos'),
  ('f-cereal', 'Cereal', 'Cereales'),
  ('f-pancakes', 'Pancakes', 'Tortitas'),
  ('f-waffles', 'Waffles', 'Gofres'),
  ('f-empanadas', 'Empanadas', 'Empanadas'),
  ('f-paella', 'Paella', 'Paella'),
  ('f-gazpacho', 'Gazpacho', 'Gazpacho'),
  ('f-hummus', 'Hummus', 'Hummus'),
  ('f-lentils', 'Lentils', 'Lentejas'),
  ('f-vegan-burgers', 'Vegan burgers', 'Hamburguesas veganas'),
  ('f-food-trucks', 'Food trucks', 'Camiones de comida'),
  ('f-tapas', 'Tapas', 'Tapas'),
  ('f-canned-food', 'Canned food', 'Comida enlatada'),
  ('f-frozen-pizza', 'Frozen pizza', 'Pizza congelada'),
  ('f-meal-prepping', 'Meal prepping', 'Preparar comidas'),
  ('f-food-delivery', 'Food delivery', 'Comida a domicilio'),
  ('f-cooking-shows', 'Cooking shows', 'Programas de cocina'),
  ('f-recipe-books', 'Recipe books', 'Libros de recetas'),
  ('f-microwaves', 'Microwaves', 'Microondas'),
  ('f-dishwashers', 'Dishwashers', 'Lavavajillas'),
  ('f-hosting-parties', 'Hosting parties', 'Dar fiestas'),
  ('f-wedding-planning', 'Wedding planning', 'Organizar bodas'),
  ('f-family-holidays', 'Family holidays', 'Vacaciones familiares'),
  ('f-office-meetings', 'Office meetings', 'Reuniones de trabajo'),
  ('f-job-interviews', 'Job interviews', 'Entrevistas de trabajo'),
  ('f-group-projects', 'Group projects', 'Proyectos en grupo'),
  ('f-deadlines', 'Deadlines', 'Fechas límite'),
  ('f-to-do-lists', 'To-do lists', 'Listas de tareas'),
  ('f-calendars', 'Calendars', 'Calendarios'),
  ('f-spreadsheets', 'Spreadsheets', 'Hojas de cálculo'),
  ('f-presentations', 'Presentations', 'Presentaciones'),
  ('f-class-reunions', 'Class reunions', 'Reencuentros escolares'),
  ('f-volunteering', 'Volunteering', 'Voluntariado'),
  ('f-charity-shops', 'Charity shops', 'Tiendas solidarias'),
  ('f-donating-money', 'Donating money', 'Donar dinero'),
  ('f-borrowing-things', 'Borrowing things', 'Pedir cosas prestadas'),
  ('f-lending-money', 'Lending money', 'Prestar dinero'),
  ('f-scented-candles', 'Scented candles', 'Velas aromáticas'),
  ('f-automatic-doors', 'Automatic doors', 'Puertas automáticas'),
  ('f-elevators', 'Elevators', 'Ascensores'),
  ('f-escalators', 'Escalators', 'Escaleras mecánicas'),
  ('f-vending-machines', 'Vending machines', 'Máquinas expendedoras'),
  ('f-reusable-bottles', 'Reusable bottles', 'Botellas reutilizables'),
  ('f-tote-bags', 'Tote bags', 'Bolsas de tela'),
  ('f-umbrellas', 'Umbrellas', 'Paraguas'),
  ('f-socks-with-sandals', 'Socks with sandals', 'Calcetines con sandalias'),
  ('f-matching-outfits', 'Matching outfits', 'Ropa a juego'),
  ('f-fancy-restaurants', 'Fancy restaurants', 'Restaurantes elegantes'),
  ('f-hotel-breakfasts', 'Hotel breakfasts', 'Desayunos de hotel'),
  ('f-window-seats', 'Window seats', 'Asientos de ventana'),
  ('f-aisle-seats', 'Aisle seats', 'Asientos de pasillo'),
  ('f-robot-vacuums', 'Robot vacuums', 'Robots aspiradores'),
  ('f-smart-homes', 'Smart homes', 'Casas inteligentes'),
  ('f-paper-books', 'Paper books', 'Libros en papel'),
  ('f-e-readers', 'E-readers', 'Lectores electrónicos'),
  ('f-vinyl-records', 'Vinyl records', 'Discos de vinilo'),
  ('f-second-hand-furniture', 'Second-hand furniture', 'Muebles de segunda mano'),
  ('f-therapy', 'Therapy', 'Terapia'),
  ('f-mental-health', 'Mental health', 'Salud mental'),
  ('f-gender-equality', 'Gender equality', 'Igualdad de género'),
  ('f-universal-basic-income', 'Universal basic income', 'Renta básica universal'),
  ('f-online-education', 'Online education', 'Educación en línea'),
  ('f-private-schools', 'Private schools', 'Colegios privados'),
  ('f-public-schools', 'Public schools', 'Colegios públicos'),
  ('f-city-living', 'City living', 'Vivir en la ciudad'),
  ('f-rural-living', 'Rural living', 'Vivir en el campo'),
  ('f-home-ownership', 'Home ownership', 'Tener casa propia'),
  ('f-renting', 'Renting', 'Vivir de alquiler'),
  ('f-having-children', 'Having children', 'Tener hijos'),
  ('f-marriage', 'Marriage', 'Matrimonio'),
  ('f-retirement', 'Retirement', 'Jubilación'),
  ('f-four-day-workweeks', 'Four-day workweeks', 'Semanas de cuatro días'),
  ('f-gap-years', 'Gap years', 'Años sabáticos'),
  ('f-higher-education', 'Higher education', 'Educación superior'),
  ('f-social-activism', 'Social activism', 'Activismo social'),
  ('f-taxes', 'Taxes', 'Impuestos'),
  ('f-censorship', 'Censorship', 'Censura'),
  ('f-online-privacy', 'Online privacy', 'Privacidad digital'),
  ('f-security-cameras', 'Security cameras', 'Cámaras de seguridad'),
  ('f-renewable-energy', 'Renewable energy', 'Energías renovables'),
  ('f-dungeons-dragons', 'Dungeons & Dragons', 'Dragones y Mazmorras'),
  ('f-opera', 'Opera', 'Ópera'),
  ('f-ballet', 'Ballet', 'Ballet'),
  ('f-classical-music', 'Classical music', 'Música clásica'),
  ('f-electronic-music', 'Electronic music', 'Música electrónica'),
  ('f-reggaeton', 'Reggaeton', 'Reguetón'),
  ('f-heavy-metal', 'Heavy metal', 'Heavy metal'),
  ('f-eurovision', 'Eurovision', 'Eurovisión'),
  ('f-cooking-competitions', 'Cooking competitions', 'Concursos de cocina'),
  ('f-owls', 'Owls', 'Búhos'),
  ('f-penguins', 'Penguins', 'Pingüinos'),
  ('f-capybaras', 'Capybaras', 'Capibaras'),
  ('f-bees', 'Bees', 'Abejas')
on conflict (id) do update
  set text_en = excluded.text_en,
      text_es = excluded.text_es;
